baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'ISARIC 4C consortium'

google_analytics_id: 'UA-177150860-1'
logo:
  mobile: "img/logo/logo_mini.svg"
  desktop: "img/logo/logo_mini.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'ISARIC 4C consortium'

seo:
  meta_og_title: "ISARIC 4C consortium"
  meta_og_type: "website"
  meta_og_url: "https://isaric4c.net"
  meta_og_image: "https://isaric4c.net/img/logo/isaric4c-logo.png"
  meta_og_description: "ISARIC 4C consortium."
  meta_twitter_card: "summary"
  meta_twitter_site: "@CCPUKstudy"
  meta_twitter_creator: "@CCPUKstudy"

collections:
  outputs:
    output: true
    permalink: /outputs/:path/
  team:
    output: true
    permalink: /team/:path/

defaults:
  - scope:
      type: outputs
    values:
      layout: output
      bodyClass: page-outputs-single
  - scope:
      path: 'img'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

destination: /tmp/isaric4c_site






