name: make_pdf

on: push

  schedule:
    - cron: '15 * * * *'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: get citeswitcher
        uses: actions/checkout@v2
        with:
          repository: baillielab/citeswitcher
          ref: develop
          path: citeswitcher

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install setuptools
          pip install wheel
          pip install pyparsing
          pip install requests
          pip install biopython
          pip install pandas
          pip install tabulate
          pip install pyyaml

      - name: fix citations
        run: |
          python citeswitcher/fixcitations.py -f _includes/ap/analysisplatform.md -l

      - name: runls
        run: |
          echo "-----"
          pwd -P
          echo "-----"
          head -70 "/home/runner/work/isaric4c.github.io/isaric4c.github.io/citeswitcher/sup-files/csl/nature.csl"
          echo "-----"
          ls citeswitcher/sup-files/csl
          echo "-----"

      - name: run_pandoc
        uses: docker://pandoc/latex
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --filter pandoc-crossref
            --citeproc
            --pdf-engine=xelatex
            --output=_includes/ap/analysisplatform.citemd.pdf
            _includes/ap/analysisplatform.yaml
            _includes/ap/analysisplatform.citemd.md

      - name: Commit if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cs.bib
          git add _includes/ap/*
          git add _includes/ap/*
          git diff-index --quiet HEAD || git commit -m "Automatically re-generate citation files"

      - name: Push files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}



